name: Release gem to RubyGems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/shared-ruby-gem-release.yml
    with:
      git_user_email: 'gems@sofwarellc.com'
      git_user_name: 'SOFware'
